/* Unternehmer Akademie v3: zusätzliche Lektionen, Übungslabor und Wiederholungen.
   Bestehende Lektionen-IDs und Supabase-Daten bleiben unverändert. */
(function(){
const bank=[
['grundlagen','Geschäftsmodell & Wertschöpfung','Ein Geschäftsmodell erklärt, für wen du welchen Nutzen schaffst und wie daraus Erlöse entstehen. Wertschöpfung ist nicht mit Umsatz gleichzusetzen: Material, Dienstleistung, Personal und Organisation müssen einen höheren Kundennutzen erzeugen als die dafür eingesetzten Mittel. Prüfe Kundengruppe, Problem, Nutzenversprechen, Vertriebskanal, Erlösmodell und Kostenstruktur.','Was gehört unmittelbar zum Geschäftsmodell?',['Nur die Firmenfarbe','Zielgruppe, Nutzen und Erlösmodell','Nur das Bankkonto'],1,'Ein Geschäftsmodell beschreibt Nutzen und wirtschaftliche Umsetzung.'],
['grundlagen','Fixkosten, variable Kosten und Mischkosten','Fixkosten fallen innerhalb eines relevanten Beschäftigungsbereichs unabhängig von der Absatzmenge an, beispielsweise eine monatliche Lagermiete. Variable Kosten verändern sich mit der Leistung, etwa Getränkeeinkauf pro verkauftem Becher. Mischkosten enthalten beide Komponenten. Wichtig: Auch Fixkosten können bei Kapazitätssprüngen steigen.','Welche Ausgabe ist typischerweise variabel?',['Monatliche Grundmiete','Wareneinsatz pro Getränk','Jährliche Domainpauschale'],1,'Wareneinsatz wächst grundsätzlich mit der Verkaufsmenge.'],
['grundlagen','Gewinn ist nicht Kontostand','Ein Betrieb kann Gewinn ausweisen, obwohl das Geld noch nicht eingegangen ist. Eine Forderung erhöht bei periodengerechter Gewinnermittlung den Ertrag, aber noch nicht die Bankliquidität. Umgekehrt ist eine Darlehensauszahlung ein Geldzufluss, aber kein betrieblicher Umsatz. Für Entscheidungen brauchst du Gewinnrechnung UND Zahlungsplanung.','Ein Kunde zahlt eine offene Rechnung erst in 60 Tagen. Was ist unmittelbar gefährdet?',['Liquidität','Firmenname','Stammkapitalhöhe'],0,'Ein später Zahlungseingang kann laufende Zahlungen gefährden.'],
['rechtsformen','Haftung im Einzelunternehmen','Ein Einzelunternehmer haftet grundsätzlich persönlich und unbeschränkt für betriebliche Verbindlichkeiten. Das betrifft auch privates Vermögen. Versicherungen, Verträge und klare Prozesse mindern einzelne Risiken, ersetzen aber keine Haftungsbegrenzung. Eine GmbH trennt grundsätzlich Gesellschaftsvermögen und Privatvermögen, kennt jedoch Ausnahmen wie persönliche Pflichtverletzungen.','Welche Aussage ist richtig?',['Einzelunternehmer haften nie privat','Einzelunternehmer haften grundsätzlich auch privat','Eine Gewerbeanmeldung begrenzt die Haftung'],1,'Beim Einzelunternehmen gibt es keine allgemeine Haftungsabschirmung.'],
['rechtsformen','GbR und Gesellschafterpflichten','Eine Gesellschaft bürgerlichen Rechts entsteht durch einen gemeinsamen Gesellschaftszweck. Bei der rechtsfähigen GbR haften Gesellschafter grundsätzlich persönlich als Gesamtschuldner. Ein Gesellschaftsvertrag sollte Beiträge, Stimmrechte, Entnahmen, Geschäftsführung, Austritt und Streitfälle regeln. Seit 2024 gibt es die Möglichkeit der Eintragung als eGbR.','Was sollte ein GbR-Vertrag regeln?',['Nur die Logofarbe','Gewinnverteilung, Zuständigkeiten und Austritt','Nur die Domain'],1,'Klare Regeln verhindern kostspielige Konflikte.'],
['rechtsformen','UG oder GmbH?','Die UG (haftungsbeschränkt) ist eine GmbH-Variante mit geringerem Stammkapital. Sie muss grundsätzlich ein Viertel ihres um Verlustvorträge geminderten Jahresüberschusses in die gesetzliche Rücklage einstellen. Die GmbH hat 25.000 € Mindeststammkapital. In beiden Fällen sind Gründungsformalitäten, Kapitalausstattung, Pflichten der Geschäftsführung und ausreichende Liquidität entscheidend.','Was unterscheidet die UG häufig von der GmbH?',['Die UG benötigt niemals Buchhaltung','Die UG kann mit geringerem Stammkapital gegründet werden','Die UG darf keine Mitarbeiter beschäftigen'],1,'Geringes Stammkapital senkt die Einstiegshürde, nicht das Geschäftsrisiko.'],
['buchhaltung','EÜR oder Bilanzierung?','Bei der Einnahmenüberschussrechnung werden grundsätzlich Betriebseinnahmen und Betriebsausgaben nach Zu- und Abfluss erfasst; Ausnahmen gelten. Bilanzierende Unternehmen ermitteln ihren Erfolg periodengerecht über Bestandskonten, Bilanz und GuV. Ob EÜR zulässig ist, hängt insbesondere von Rechtsform und gesetzlichen Buchführungspflichten ab.','Welche Aussage passt zur EÜR?',['Sie orientiert sich grundsätzlich an Zahlungen','Sie ist für jede GmbH frei wählbar','Sie ersetzt jede Aufbewahrungspflicht'],0,'Die EÜR ist grundsätzlich zahlungsorientiert.'],
['buchhaltung','Umsatzsteuer und Vorsteuer','Umsatzsteuer wird auf steuerpflichtige Ausgangsleistungen berechnet. Vorsteuer aus ordnungsgemäßen Eingangsrechnungen kann bei erfüllten Voraussetzungen abziehbar sein. Die Zahllast ergibt sich vereinfacht aus Umsatzsteuer minus abziehbarer Vorsteuer. Bei Kleinunternehmern gelten besondere Regeln. Brutto- und Nettowerte darfst du nie unbemerkt vermischen.','19 € Umsatzsteuer und 8 € abziehbare Vorsteuer ergeben welche Zahllast?',['27 €','11 €','8 €'],1,'19 minus 8 ergibt 11 €.'],
['buchhaltung','Abschreibung verstehen','Die Anschaffung einer länger nutzbaren Maschine ist nicht automatisch vollständig Aufwand im Kaufjahr. Bei abnutzbaren Anlagegütern verteilen Abschreibungen die Anschaffungskosten grundsätzlich über die Nutzungsdauer. Der Kauf beeinflusst die Liquidität sofort; die Abschreibung verteilt den Aufwand. Sonderregelungen können gelten.','Was beschreibt eine planmäßige Abschreibung?',['Aufwandverteilung über die Nutzungsdauer','Immer eine monatliche Auszahlung','Die Tilgung eines Darlehens'],0,'Abschreibung ist regelmäßig nicht zahlungswirksam.'],
['cashflow','Liquiditätsplan erstellen','Ein Liquiditätsplan zeigt für jede Woche oder jeden Monat Anfangsbestand, erwartete Einzahlungen, fällige Auszahlungen und Endbestand. Plane nicht nur die Umsätze, sondern tatsächliche Zahlungstermine. Berücksichtige Steuerzahlungen, Löhne, Lieferanten, Darlehen und eine Reserve. Rechne zusätzlich mit einem pessimistischen Szenario.','Was gehört in einen Liquiditätsplan?',['Nur gestellte Rechnungen','Tatsächliche erwartete Zahlungstermine','Nur den Jahresgewinn'],1,'Liquidität hängt von Zahlungszeitpunkten ab.'],
['cashflow','Forderungen und Zahlungsziele','Lange Zahlungsziele binden Kapital. Wenn Lieferanten früher bezahlt werden müssen als Kunden zahlen, entsteht eine Finanzierungslücke. Gegenmaßnahmen sind Anzahlungen, kürzere Zahlungsziele, Mahnprozesse, Reserven oder geeignete Finanzierung. Ein höherer Umsatz kann den Liquiditätsbedarf sogar vergrößern.','Welche Maßnahme verkürzt den Geldzufluss?',['Längere Kundenzahlungsziele','Frühere Anzahlungen','Späteres Mahnen'],1,'Anzahlungen bringen Geld vor Leistungserbringung.'],
['kalkulation','Deckungsbeitrag pro Auftrag','Der Deckungsbeitrag ist Umsatz minus variable Kosten. Er zeigt, welcher Betrag zur Deckung fixer Kosten und danach zum Gewinn beiträgt. Ein positiver Deckungsbeitrag bedeutet noch nicht, dass der Auftrag insgesamt profitabel ist. Auch Engpässe, Kapazität und zusätzliche Fixkosten zählen.','Auftrag 1.000 €, variable Kosten 650 €: Deckungsbeitrag?',['350 €','650 €','1.650 €'],0,'1.000 minus 650 ergibt 350 €.'],
['kalkulation','Stundensatz realistisch planen','Ein tragfähiger Stundensatz deckt produktive Arbeitszeit, Lohnkosten, Ausfallzeiten, Gemeinkosten, Fahrzeuge, Verwaltung, Risiko und gewünschten Gewinn. Nicht jede bezahlte Stunde ist fakturierbar. Kalkuliere mit realistisch verkaufbaren Stunden und überprüfe Nachkalkulationen.','Warum ist ein Stundensatz von 15 € bei 15 € Stundenlohn oft zu niedrig?',['Weil zusätzliche Arbeitgeber- und Gemeinkosten fehlen','Weil Umsatz gleich Gewinn ist','Weil die Steuer immer 50 % beträgt'],0,'Lohn ist nur ein Teil der gesamten Kosten.'],
['personal','Arbeitgeberkosten','Zusätzlich zum Bruttolohn entstehen je nach Beschäftigung Arbeitgeberanteile zur Sozialversicherung, Umlagen, Unfallversicherung und weitere Kosten. Arbeitszeitdokumentation, Urlaubsansprüche, Mindestlohn und Meldepflichten sind gesondert zu beachten. Kalkuliere niemals nur den ausgezahlten Nettolohn.','Welche Kalkulation ist sinnvoll?',['Nur Nettolohn','Bruttolohn plus weitere Arbeitgeberkosten','Nur Trinkgeld'],1,'Der tatsächliche Personalaufwand ist höher als der Nettolohn.'],
['personal','Delegation und Kontrolle','Delegation bedeutet, Aufgaben und Entscheidungsspielräume klar zu übertragen. Die Verantwortung für Kontrolle und Organisation verschwindet dadurch nicht. Definiere Ziel, Budget, Termin, Zuständigkeit und Qualitätskriterien. Prüfe Ergebnisse anhand messbarer Kennzahlen statt durch ständige Einzelanweisungen.','Was gehört zu guter Delegation?',['Unklare Verantwortung','Klares Ziel und definierte Befugnisse','Keine Rückmeldung'],1,'Klare Zuständigkeiten reduzieren Fehler.'],
['finanzierung','Eigenkapital, Darlehen und Leasing','Eigenkapital steht dem Unternehmen ohne festen Rückzahlungstermin zur Verfügung, trägt aber das unternehmerische Risiko. Darlehen bringen Liquidität und führen zu Zins- und Tilgungsverpflichtungen. Leasing verteilt Nutzungszahlungen, kann aber über die Laufzeit teuer sein. Vergleiche Gesamtkosten, Sicherheiten und Liquiditätseffekt.','Was ist bei einem Darlehen besonders zu planen?',['Zins und Tilgung','Nur der Firmenname','Nur die Rechnungsvorlage'],0,'Zahlungsverpflichtungen müssen in den Liquiditätsplan.'],
['finanzierung','Investitionsrechnung','Bei Investitionen zählen Anschaffung, laufende Kosten, Nutzungsdauer, Restwert und zusätzliche Einzahlungen. Eine einfache Amortisationsrechnung beantwortet, wann sich eine Ausgabe zurückverdient; sie berücksichtigt aber nicht automatisch Zeitwert, Risiko oder Alternativen. Bei großen Beträgen helfen Kapitalwert und Szenarien.','Was wird bei einer Investition zusätzlich zum Kaufpreis betrachtet?',['Nur die Farbe','Laufende Kosten und erwartete Rückflüsse','Nur die Lieferzeit'],1,'Wirtschaftlichkeit umfasst den gesamten Lebenszyklus.'],
['strategie','Kennzahlen richtig einsetzen','Kennzahlen helfen bei Entscheidungen, wenn sie regelmäßig und einheitlich berechnet werden. Beispiele: Umsatzentwicklung, Deckungsbeitrag, Liquiditätsreichweite, Forderungslaufzeit, Reklamationen und Auslastung. Einzelwerte ohne Vergleich oder Kontext führen leicht in die Irre.','Welche Kennzahl hilft bei kurzfristiger Zahlungsfähigkeit?',['Liquiditätsreichweite','Anzahl Logoentwürfe','Follower allein'],0,'Die Liquiditätsreichweite betrachtet verfügbare Mittel und Mittelabfluss.'],
['strategie','Risiko und Notfallplanung','Erstelle eine Risikoliste mit Eintrittswahrscheinlichkeit, Schadenshöhe, Frühwarnzeichen und Gegenmaßnahmen. Typische Risiken sind Forderungsausfälle, Personalausfall, Haftung, IT-Ausfall und Abhängigkeit von wenigen Kunden. Bestimme für kritische Prozesse einen Notfallplan und Verantwortliche.','Was gehört zu einer Risikobewertung?',['Eintrittswahrscheinlichkeit und Schaden','Nur die Stimmung','Nur die Werbekosten'],0,'Risiken müssen nach Eintritt und Auswirkung bewertet werden.']
];
const extra={
'gruendung':['Gewerbeanmeldung & Behörden','Ein Gewerbe muss grundsätzlich bei der zuständigen Behörde angemeldet werden. Weitere Erlaubnisse können von der konkreten Tätigkeit abhängen. Die steuerliche Erfassung läuft über das Finanzamt. Prüfe auch Berufsgenossenschaft, Versicherungen und kommunale Vorgaben.','Welche Aussage stimmt?',['Jede Tätigkeit ist ohne Erlaubnis möglich','Je nach Tätigkeit sind zusätzliche Genehmigungen nötig','Eine Domain ersetzt die Gewerbeanmeldung'],1,'Die Pflichten hängen von der Tätigkeit ab.'],
'controlling':['Budget und Soll-Ist-Vergleich','Ein Budget definiert geplante Einnahmen, Ausgaben und Ziele. Vergleiche monatlich Ist-Zahlen mit dem Plan und untersuche Abweichungen nach Preis, Menge und Kosten. Leite konkrete Maßnahmen ab, statt nur rote Zahlen zu markieren.','Wozu dient ein Soll-Ist-Vergleich?',['Abweichungen erkennen und steuern','Passwörter speichern','Steuern automatisch abschaffen'],0,'Abweichungen liefern Ansatzpunkte für Maßnahmen.'],
'vertrieb':['Angebot, Preis und Kundennutzen','Vertrieb beginnt beim Kundenproblem. Beschreibe Nutzen, Leistungsumfang, Preis, Bedingungen und nächsten Schritt verständlich. Messe nicht nur Kontakte, sondern Angebotsquote, Abschlussquote und Deckungsbeitrag pro Auftrag.','Welche Zahl zeigt Vertriebserfolg besser als reine Reichweite?',['Abschlussquote','Anzahl Bildschirmhintergründe','Nur Seitenaufrufe'],0,'Abschlüsse zeigen, ob Interesse zu Aufträgen führt.'],
'recht':['Verträge und Haftungsrisiken','Verträge sollten Leistung, Preis, Fristen, Zahlungsbedingungen, Abnahme und Haftung klar regeln. Bei personenbezogenen Daten sind Datenschutzpflichten zu beachten. Standardtexte ersetzen keine Prüfung des konkreten Falls.','Was reduziert Streit über einen Auftrag?',['Unklare mündliche Zusagen','Schriftlich definierter Leistungsumfang','Fehlende Zahlungsbedingungen'],1,'Klare Vereinbarungen helfen beiden Seiten.']
};
for(const [id,arr] of Object.entries(extra)){modules.push({id,n:modules.length+1,title:({gruendung:'Gründung & Behörden',controlling:'Controlling & Budget',vertrieb:'Vertrieb & Marketing',recht:'Wirtschaftsrecht'})[id],desc:arr[1].slice(0,95)+'…',icon:'◆',lessons:[{id:'plus-'+id,title:arr[0],xp:90,body:'<p>'+arr[1]+'</p><h3>Transfer in die Praxis</h3><p>Notiere, wie du dieses Wissen in einem eigenen Auftrag anwenden würdest.</p>',q:{text:arr[2],opts:arr[3],correct:arr[4],why:arr[5]}}]});}
for(let i=0;i<bank.length;i++){const [mid,title,body,question,opts,correct,why]=bank[i];const m=modules.find(x=>x.id===mid);if(m)m.lessons.push({id:'plus-'+mid+'-'+i,title,xp:80,body:`<p>${body}</p><h3>Praxisübertragung</h3><p>Formuliere ein eigenes Beispiel aus deinem Unternehmen. Welche Zahlen oder Unterlagen benötigst du für eine Entscheidung?</p>`,q:{text:question,opts,correct,why}});}
const cases=[
{id:'event',title:'Event: Ist der Auftrag rentabel?',area:'Kalkulation',story:'Ein Veranstalter zahlt netto 4.800 €. Wareneinsatz: 1.250 €, Personal: 600 €, sonstige Auftragskosten: 850 €. Keine weiteren Kosten.',question:'Wie hoch ist der vereinfachte Gewinn vor Steuern in Euro?',answer:2100,explain:'4.800 − 1.250 − 600 − 850 = 2.100 €. Fixe Jahreskosten und Unternehmerlohn sind hier ausdrücklich nicht enthalten.'},
{id:'cash',title:'Gewinn ohne Geld auf dem Konto',area:'Liquidität',story:'Anfangsbestand 3.000 €. Diese Woche zahlen Kunden 1.500 € ein. Lieferanten und Löhne sind zusammen mit 4.200 € fällig.',question:'Wie hoch ist der Endbestand in Euro?',answer:300,explain:'3.000 + 1.500 − 4.200 = 300 €. Offene, noch nicht bezahlte Rechnungen helfen beim Bezahlen heute nicht.'},
{id:'db',title:'Auftragsentscheidung: Deckungsbeitrag',area:'Kalkulation',story:'Ein Zusatzauftrag bringt 2.400 € netto Umsatz. Direkt zurechenbare variable Kosten betragen 1.550 €.',question:'Wie hoch ist der Deckungsbeitrag in Euro?',answer:850,explain:'2.400 − 1.550 = 850 €. Damit sind noch nicht sämtliche fixen Unternehmenskosten gedeckt.'},
{id:'break',title:'Break-even eines Produkts',area:'Controlling',story:'Monatliche Fixkosten: 1.200 €. Nettoverkaufspreis je Stück: 15 €. Variable Stückkosten: 9 €.',question:'Wie viele Stück musst du mindestens verkaufen, um die Fixkosten zu decken?',answer:200,explain:'Deckungsbeitrag 15 − 9 = 6 € pro Stück. 1.200 / 6 = 200 Stück.'},
{id:'vat',title:'Vorsteuer und Zahllast',area:'Steuern',story:'Du hast 1.900 € Umsatzsteuer auf Ausgangsrechnungen und 760 € abzugsfähige Vorsteuer auf Eingangsrechnungen.',question:'Wie hoch ist die vereinfachte Umsatzsteuerzahllast in Euro?',answer:1140,explain:'1.900 − 760 = 1.140 €. Das setzt vollständige Vorsteuerabzugsberechtigung voraus.'},
{id:'loan',title:'Darlehen und Liquidität',area:'Finanzierung',story:'Du erhältst ein Darlehen von 12.000 €. Im selben Monat zahlst du 2.000 € Tilgung und 100 € Zinsen. Sonst keine Zahlungen.',question:'Wie hoch ist der Netto-Zahlungszufluss in Euro?',answer:9900,explain:'12.000 − 2.000 − 100 = 9.900 €. Das Darlehen ist kein Umsatz und die Tilgung kein gewöhnlicher Betriebsaufwand.'}
];
let selected=cases[0].id;
const key=()=>`akademie-v3-confidence-${user?.id||'guest'}`;
const conf=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};
window.setConfidence=function(id,value){let x=conf();x[id]=value;localStorage.setItem(key(),JSON.stringify(x));toast(value==='unsicher'?'Für Wiederholung vorgemerkt':'Als sicher markiert');renderReview()};
window.renderReview=function(){const x=conf(),wrong=new Set(state.answers.filter(a=>!a.is_correct).map(a=>a.lesson_id));const ls=allLessons().filter(l=>wrong.has(l.id)||x[l.id]==='unsicher');$('#content').innerHTML=`<div class="card"><h3>Dein Wiederholungszentrum</h3><p>Jede Lektion kannst du beliebig oft üben. Bestehende XP bleiben erhalten. Markiere Inhalte als unsicher, damit du sie hier wiederfindest.</p><button class="primary" onclick="show('learn')">Alle Lektionen öffnen →</button> <button class="btn" onclick="show('practice')">Praxislabor öffnen →</button></div><div class="grid">${ls.map(l=>`<div class="card third"><span class="tag">WIEDERHOLEN</span><h3>${l.title}</h3><p>${l.module.title}</p><button class="btn" onclick="openLesson('${l.module.id}','${l.id}')">Erneut üben</button> <button class="btn secondary" onclick="setConfidence('${l.id}','sicher')">Jetzt sicher ✓</button></div>`).join('')||'<div class="card wide"><h3>Keine offenen Wiederholungen</h3><p>Du kannst jederzeit über den Lernpfad jede abgeschlossene Lektion erneut öffnen.</p></div>'}</div>`};
const oldOpen=openLesson;
window.openLesson=function(mid,lid){oldOpen(mid,lid);const el=document.querySelector('#content .lesson');if(el){const box=document.createElement('section');box.className='card';box.innerHTML=`<h3>Wie sicher fühlst du dich?</h3><p>Deine Selbsteinschätzung ändert keine XP und keinen Abschluss.</p><button class="btn" onclick="setConfidence('${lid}','unsicher')">↻ Noch unsicher</button> <button class="btn secondary" onclick="setConfidence('${lid}','sicher')">✓ Sitzt sicher</button>`;el.appendChild(box)}};
window.renderPractice=function(){const c=cases.find(x=>x.id===selected);$('#content').innerHTML=`<div class="grid"><section class="card third"><span class="tag">PRAXISLABOR</span><h3>Fall auswählen</h3>${cases.map(x=>`<button class="case-choice ${x.id===selected?'selected':''}" onclick="selectCase('${x.id}')">${x.title}<small>${x.area}</small></button>`).join('')}</section><section class="card half"><span class="tag">${c.area.toUpperCase()}</span><h2>${c.title}</h2><p>${c.story}</p><h3>${c.question}</h3><label>Deine Antwort <input id="caseAnswer" type="number" step="any" placeholder="Zahl eingeben"></label><button class="primary" onclick="checkCase()">Lösung prüfen</button><div id="caseResult"></div><p class="muted">Übe beliebig oft. Praxisfälle vergeben bewusst keine zusätzlichen XP.</p></section><section class="card third"><h3>So lernst du</h3><p>1. Fall lesen<br>2. Selbst rechnen<br>3. Lösung nachvollziehen<br>4. Erneut probieren</p><button class="btn" onclick="show('review')">Meine Wiederholungen</button></section></div>`};
window.selectCase=function(id){selected=id;renderPractice()};
window.checkCase=function(){const c=cases.find(x=>x.id===selected),raw=$('#caseAnswer').value;if(raw===''){toast('Bitte eine Zahl eingeben');return}const ok=Math.abs(Number(raw)-c.answer)<0.005;$('#caseResult').innerHTML=`<div class="result"><b>${ok?'✓ Richtig!':'Noch nicht richtig.'}</b><p>${c.explain}</p><button class="btn secondary" onclick="selectCase('${selected}')">Fall wiederholen ↻</button></div>`};
const oldShow=show;
window.show=function(v){if(v==='practice'){$$('aside [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#title').textContent='Praxislabor';$('#crumb').textContent='AKADEMIE';renderPractice();window.scrollTo(0,0)}else oldShow(v)};
const nav=document.querySelector('aside nav');const btn=document.createElement('button');btn.dataset.view='practice';btn.innerHTML='▣ <span>Praxislabor</span>';btn.addEventListener('click',()=>show('practice'));nav.insertBefore(btn,nav.querySelector('[data-view="review"]'));
const mnav=document.querySelector('.mobile-nav');if(mnav){const mb=document.createElement('button');mb.dataset.view='practice';mb.innerHTML='▣<small>Praxis</small>';mb.addEventListener('click',()=>show('practice'));mnav.appendChild(mb)}
})();
