const cfg=window.APP_CONFIG||{};let sb=null,user=null,state={progress:[],answers:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const modules=[
 {id:'grundlagen',n:1,title:'Unternehmer: Grundlagen',desc:'Umsatz, Kosten, Gewinn, Vermögen und Liquidität.',icon:'◈',lessons:[
  {id:'umsatz-gewinn',title:'Umsatz ist nicht Gewinn',xp:50,body:`<h3>Die vier Grundbegriffe</h3><p><b>Umsatz</b> ist der Wert deiner verkauften Waren und Leistungen. <b>Kosten</b> sind die betrieblich verursachten Aufwendungen. Vereinfacht gilt: Umsatz minus Kosten = Gewinn oder Verlust.</p><p><b>Liquidität</b> beantwortet eine andere Frage: Kann das Unternehmen seine fälligen Rechnungen tatsächlich bezahlen? Ein Unternehmen kann Gewinn ausweisen und trotzdem zu wenig Geld auf dem Konto haben, etwa wenn Kunden spät zahlen.</p><h3>Merksatz</h3><p>Gewinn misst wirtschaftlichen Erfolg. Liquidität misst Zahlungsfähigkeit. Beides gehört zusammen, ist aber nicht dasselbe.</p>`,q:{text:'Dein Betrieb schreibt Gewinn, aber ein großer Kunde zahlt erst in 90 Tagen. Was kann trotzdem knapp werden?',opts:['Umsatz','Liquidität','Eigenkapitalquote','Stammkapital'],correct:1,why:'Der Gewinn kann bereits entstanden sein, obwohl das Geld noch nicht eingegangen ist. Dadurch kann die Liquidität fehlen.'}},
  {id:'kosten',title:'Fixe und variable Kosten',xp:50,body:`<p><b>Fixkosten</b> verändern sich kurzfristig nicht direkt mit der Absatzmenge, z. B. Miete. <b>Variable Kosten</b> steigen typischerweise mit Produktion oder Verkauf, z. B. Wareneinsatz.</p><p>Diese Trennung ist wichtig für Deckungsbeitrag und Break-even.</p>`,q:{text:'Welche Kosten sind bei einer Veranstaltung am ehesten variabel?',opts:['Jahresbeitrag Versicherung','Getränkeeinkauf je verkauftem Getränk','Monatliche Büromiete','Grundgebühr Software'],correct:1,why:'Der Getränkeeinsatz hängt direkt von der verkauften Menge ab.'}}
 ]},
 {id:'rechtsformen',n:2,title:'Rechtsformen',desc:'Einzelunternehmen, GbR, UG, GmbH und mehr.',icon:'§',lessons:[
  {id:'einzel-gbr',title:'Einzelunternehmen & GbR',xp:60,body:`<p>Beim <b>Einzelunternehmen</b> gibt es einen Inhaber. Eine <b>GbR</b> entsteht grundsätzlich durch den Zusammenschluss von mindestens zwei Personen zur Förderung eines gemeinsamen Zwecks.</p><p>Die Wahl der Rechtsform beeinflusst unter anderem Haftung, Kapitalbedarf, Organisation, Publizität und Besteuerung. Sie sollte deshalb nicht nur nach Gründungskosten gewählt werden.</p>`,q:{text:'Welcher Punkt ist bei der Wahl einer Rechtsform besonders wichtig?',opts:['Nur das Logo','Haftung und Organisation','Die Farbe der Rechnungen','Die Bankkarte'],correct:1,why:'Haftung und organisatorische Anforderungen gehören zu den zentralen Kriterien.'}},
  {id:'ug-gmbh',title:'UG & GmbH',xp:70,body:`<p>Die GmbH ist eine Kapitalgesellschaft. Das gesetzliche Stammkapital beträgt 25.000 €. Die UG (haftungsbeschränkt) ist eine Variante der GmbH und kann mit geringerem Stammkapital gegründet werden, muss aber gesetzliche Rücklagen bilden.</p><p>Beschränkte Haftung bedeutet nicht, dass Geschäftsführer niemals persönlich haften. Pflichtverletzungen können persönliche Folgen haben.</p>`,q:{text:'Wie hoch ist das gesetzliche Stammkapital einer GmbH?',opts:['1 €','5.000 €','25.000 €','50.000 €'],correct:2,why:'Das GmbHG sieht 25.000 € Stammkapital vor.'}}
 ]},
 {id:'buchhaltung',n:3,title:'Buchhaltung & Steuern',desc:'EÜR, GuV, Bilanz, Umsatzsteuer und Abschreibung.',icon:'▦',lessons:[
  {id:'eur-guv',title:'EÜR, GuV und Bilanz',xp:70,body:`<p>Die <b>EÜR</b> ermittelt den Gewinn grundsätzlich über Betriebseinnahmen minus Betriebsausgaben. Bei doppelter Buchführung werden Geschäftsvorfälle systematisch erfasst; GuV und Bilanz bilden zentrale Bestandteile des Jahresabschlusses.</p><p>Welche Methode zulässig oder vorgeschrieben ist, hängt von Rechtsform und gesetzlichen Voraussetzungen ab.</p>`,q:{text:'Was stellt eine Bilanz gegenüber?',opts:['Einnahmen und Urlaub','Vermögen und Kapital','Nur Umsatz und Steuer','Kunden und Lieferanten'],correct:1,why:'Die Bilanz stellt auf der Aktivseite Vermögen und auf der Passivseite dessen Finanzierung bzw. Kapital gegenüber.'}},
  {id:'ust',title:'Umsatzsteuer verstehen',xp:70,body:`<p>Unternehmer vereinnahmen häufig Umsatzsteuer auf Ausgangsleistungen und können unter Voraussetzungen Vorsteuer aus Eingangsleistungen abziehen. Die Differenz wird gegenüber dem Finanzamt abgerechnet.</p><p>Umsatzsteuer ist daher nicht einfach zusätzlicher Unternehmensgewinn.</p>`,q:{text:'Ist vereinnahmte Umsatzsteuer automatisch dein Gewinn?',opts:['Ja','Nein'],correct:1,why:'Sie ist grundsätzlich eine Steuerposition und nicht einfach zusätzlicher Gewinn.'}}
 ]},
 {id:'cashflow',n:4,title:'Cashflow & Liquidität',desc:'Zahlungsströme, Working Capital und Liquiditätsplanung.',icon:'€',lessons:[
  {id:'cashflow-basic',title:'Cashflow verstehen',xp:80,body:`<p>Cashflow betrachtet Zahlungsströme. In der Praxis werden operative, Investitions- und Finanzierungstätigkeit getrennt betrachtet. So erkennst du, wodurch Geld tatsächlich hinein- oder hinausfließt.</p><p>Eine Liquiditätsplanung schaut zusätzlich nach vorn: Welche Ein- und Auszahlungen werden wann fällig?</p>`,q:{text:'Warum kann Gewinn höher sein als der aktuelle Geldzufluss?',opts:['Weil Forderungen noch nicht bezahlt wurden','Weil Gewinn immer Bargeld ist','Weil Kosten nie bezahlt werden','Das ist unmöglich'],correct:0,why:'Ein Umsatz kann erfolgswirksam erfasst sein, bevor der Kunde tatsächlich bezahlt.'}}
 ]},
 {id:'kalkulation',n:5,title:'Kalkulation & Kennzahlen',desc:'Deckungsbeitrag, Break-even, Marge und ROI.',icon:'%',lessons:[
  {id:'deckungsbeitrag',title:'Deckungsbeitrag',xp:80,body:`<p>Der Deckungsbeitrag zeigt vereinfacht, welcher Betrag nach Abzug variabler Kosten zur Deckung fixer Kosten und anschließend für Gewinn verbleibt.</p><p>Stückdeckungsbeitrag = Verkaufspreis je Stück − variable Kosten je Stück.</p>`,q:{text:'Preis 10 €, variable Kosten 4 €. Stückdeckungsbeitrag?',opts:['4 €','6 €','10 €','14 €'],correct:1,why:'10 € − 4 € = 6 €.'}}
 ]},
 {id:'personal',n:6,title:'Personal & Arbeitgeber',desc:'Beschäftigung, Arbeitgeberkosten und Führung.',icon:'♟',lessons:[
  {id:'ag-kosten',title:'Was Mitarbeiter wirklich kosten',xp:80,body:`<p>Für die Personalkalkulation reicht der vereinbarte Bruttolohn nicht. Je nach Beschäftigungsart kommen Arbeitgeberanteile, Umlagen, Versicherungen sowie indirekte Kosten hinzu.</p><p>Für Angebote sollte deshalb mit realistischen Arbeitgeber- und produktiven Stundenkosten gerechnet werden.</p>`,q:{text:'Solltest du Angebote nur mit dem Bruttostundenlohn eines Mitarbeiters kalkulieren?',opts:['Ja','Nein'],correct:1,why:'Arbeitgeber- und weitere betriebliche Kosten müssen in einer belastbaren Kalkulation berücksichtigt werden.'}}
 ]},
 {id:'finanzierung',n:7,title:'Finanzierung & Investition',desc:'Eigenkapital, Fremdkapital, Leasing und ROI.',icon:'◇',lessons:[
  {id:'roi',title:'Investitionen bewerten',xp:90,body:`<p>Eine Investition sollte nicht nur nach dem Kaufpreis bewertet werden. Relevant sind Zahlungszeitpunkte, laufende Kosten, erwarteter Nutzen, Risiken und Alternativen.</p><p>Der ROI ist eine Kennzahl, aber keine Kristallkugel. Zukunftsannahmen bleiben Annahmen, wie Menschen regelmäßig auf schmerzhafte Weise entdecken.</p>`,q:{text:'Was gehört zu einer Investitionsentscheidung?',opts:['Nur Kaufpreis','Kosten, Nutzen, Zahlungszeitpunkte und Risiken','Nur Umsatz','Nur Steuer'],correct:1,why:'Eine Investition muss ganzheitlich betrachtet werden.'}}
 ]},
 {id:'strategie',n:8,title:'Strategie & Wachstum',desc:'Prozesse, Skalierung, Risiken und Geschäftsführerdenken.',icon:'▲',lessons:[
  {id:'skalierung',title:'Wachstum ohne Chaos',xp:100,body:`<p>Wachstum erhöht nicht nur Umsatz, sondern oft auch Komplexität. Wiederholbare Prozesse, Verantwortlichkeiten, Kennzahlen und ausreichende Liquidität werden wichtiger.</p><p>Ein guter Prozess macht das Unternehmen weniger abhängig davon, dass eine einzelne Person alles im Kopf trägt.</p>`,q:{text:'Was hilft bei gesundem Wachstum?',opts:['Alles selbst machen','Klare Prozesse und Verantwortlichkeiten','Keine Kennzahlen','Liquidität ignorieren'],correct:1,why:'Standardisierte Prozesse und klare Verantwortung reduzieren operative Abhängigkeiten.'}}
 ]}
];
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function allLessons(){return modules.flatMap(m=>m.lessons.map(l=>({...l,module:m})))}
function completed(){return new Set(state.progress.filter(x=>x.completed).map(x=>x.lesson_id))}
function xp(){return state.progress.reduce((a,x)=>a+(x.xp_earned||0),0)}function level(){return Math.floor(xp()/250)+1}
async function init(){try{if(!cfg.SUPABASE_URL||cfg.SUPABASE_URL.includes('DEIN-'))throw Error('config.js noch nicht eingerichtet');sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);let {data:{session}}=await sb.auth.getSession();if(session)await enter(session.user);else{$('#login').innerHTML='<div class="auth-card"><h2>Bitte zuerst bei Rudelbar anmelden</h2><p>Öffne die Akademie über deine Rudelbar-App.</p></div>';}sb.auth.onAuthStateChange((_e,s)=>{if(!s){$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}})}catch(e){toast(e.message)}}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();toast('Bitte über die Rudelbar-App anmelden.');});
async function enter(u){
  user=u;
  const {data:role,error:roleError}=await sb.rpc('get_rudelbar_role');
  const isAdmin=!roleError&&role==='superuser';
  if(!isAdmin){
    const {data:allowed,error:permissionError}=await sb.from('academy_access').select('area').eq('user_id',u.id);
    if(permissionError){$('#login').classList.remove('hidden');$('#login').innerHTML='<div class="auth-card"><h2>Akademie noch nicht eingerichtet</h2><p>Die Datenbankfreigaben fehlen oder konnten nicht geladen werden. Bitte Superuser informieren.</p></div>';return;}
    const grants=new Set((allowed||[]).map(x=>x.area));
    const area=m=>m.id==='marketing'?'marketing':m.id==='mobile-kneipe'?'mobile-kneipe':m.id==='security-34a'?'security':'unternehmer';
    for(let i=modules.length-1;i>=0;i--)if(!grants.has(area(modules[i])))modules.splice(i,1);
    if(!grants.has('security')) document.querySelectorAll('aside nav button').forEach(b=>{if(b.textContent.includes('34a'))b.remove()});
    if(!modules.length){$('#login').classList.remove('hidden');$('#login').innerHTML='<div class="auth-card"><h2>Keine Lernfelder freigegeben</h2><p>Ein Superuser kann dir in der Rudelbar-Teamverwaltung Lernbereiche freigeben.</p></div>';return;}
  }
  $('#login').classList.add('hidden');$('#app').classList.remove('hidden');await loadState();show('dashboard')}
async function loadState(){let {data:p}=await sb.from('progress').select('*').eq('user_id',user.id);let {data:a}=await sb.from('quiz_answers').select('*').eq('user_id',user.id);state.progress=p||[];state.answers=a||[];updateTop()}
function updateTop(){$('#xpTop').textContent=xp()+' XP';$('#levelBadge').textContent='Level '+level()}
$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#logout').onclick=()=>{window.parent?.postMessage({type:'rudelbar-academy-close'},window.location.origin)};
function show(v){$$('aside [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));let titles={dashboard:'Dashboard',learn:'Lernpfad',review:'Wiederholen',tools:'Unternehmer-Rechner',simulation:'Unternehmenssimulation',profile:'Statistiken'};$('#title').textContent=titles[v];$('#crumb').textContent=v==='dashboard'?'ÜBERSICHT':'AKADEMIE';({dashboard:renderDash,learn:renderLearn,review:renderReview,tools:renderTools,simulation:renderSimulation,profile:renderProfile}[v])();scrollTo(0,0)}
function renderDash(){let done=completed().size,total=allLessons().length,pct=Math.round(done/total*100),next=allLessons().find(l=>!completed().has(l.id));$('#content').innerHTML=`<div class="grid"><section class="card hero"><span class="tag">DEIN LERNPFAD</span><h3>Willkommen zurück, Bärchen! 👋</h3><p>Vom Gründerwissen bis zum Geschäftsführer-Level. Lernen, verstehen und direkt anwenden.</p><button class="primary" onclick="${next?`openLesson('${next.module.id}','${next.id}')`:`show('learn')`}">${next?'Lektion fortsetzen →':'Lernpfad ansehen →'}</button></section><section class="card stats"><div style="display:flex;gap:18px;align-items:center"><div class="ring" style="--p:${pct}%"><b>${pct}%</b></div><div><span class="muted">Gesamtfortschritt</span><h3>Level ${level()}</h3><b>${xp()} XP</b></div></div></section><div class="card quarter metric"><span class="muted">Lektionen</span><br><strong>${done}</strong><p class="muted">von ${total} abgeschlossen</p></div><div class="card quarter metric"><span class="muted">Module</span><br><strong>${modules.filter(m=>m.lessons.every(l=>completed().has(l.id))).length}</strong><p class="muted">vollständig gemeistert</p></div><div class="card quarter metric"><span class="muted">Richtige Antworten</span><br><strong>${state.answers.filter(a=>a.is_correct).length}</strong><p class="muted">Wissenschecks</p></div><div class="card quarter metric"><span class="muted">Nächstes Ziel</span><br><strong>${250-(xp()%250||250)}</strong><p class="muted">XP bis zum Level-Up</p></div><section class="card wide"><h3>Dein Lernpfad</h3><div class="grid">${modules.slice(0,4).map(m=>moduleCard(m,'quarter')).join('')}</div></section></div>`}
function moduleCard(m,cls='third'){let d=m.lessons.filter(l=>completed().has(l.id)).length,p=Math.round(d/m.lessons.length*100);return `<div class="card module ${cls}" onclick="openModule('${m.id}')"><span class="num">MODUL ${String(m.n).padStart(2,'0')} · ${m.icon}</span><h3>${m.title}</h3><p>${m.desc}</p><div class="progress"><i style="width:${p}%"></i></div><p class="muted">${d}/${m.lessons.length} Lektionen</p></div>`}
function renderLearn(){$('#content').innerHTML=`<div class="grid">${modules.map(m=>moduleCard(m)).join('')}</div>`}
function openModule(id){let m=modules.find(x=>x.id===id);$('#title').textContent=m.title;$('#content').innerHTML=`<div class="lesson"><button class="btn secondary" onclick="show('learn')">← Lernpfad</button><div class="card"><h3>${m.title}</h3><p>${m.desc}</p>${m.lessons.map((l,i)=>`<div class="stat-row"><span>${completed().has(l.id)?'✓':'○'} ${i+1}. ${l.title}</span><button class="btn" onclick="openLesson('${m.id}','${l.id}')">${completed().has(l.id)?'Wiederholen':'Starten'}</button></div>`).join('')}</div></div>`;scrollTo(0,0)}
function openLesson(mid,lid){let m=modules.find(x=>x.id===mid),l=m.lessons.find(x=>x.id===lid);$('#title').textContent=l.title;$('#content').innerHTML=`<div class="lesson"><button class="btn secondary" onclick="openModule('${mid}')">← ${m.title}</button><section class="card"><span class="tag">+${l.xp} XP</span><article><h2>${l.title}</h2>${l.body}</article></section><section class="card"><h3>Wissenscheck</h3><p>${l.q.text}</p><div id="opts">${l.q.opts.map((o,i)=>`<button class="quiz-option" onclick="answer('${mid}','${lid}',${i})">${o}</button>`).join('')}</div><div id="feedback"></div></section></div>`;scrollTo(0,0)}
async function answer(mid,lid,choice){let m=modules.find(x=>x.id===mid),l=m.lessons.find(x=>x.id===lid),ok=choice===l.q.correct;$$('.quiz-option').forEach((b,i)=>{b.disabled=true;if(i===l.q.correct)b.classList.add('correct');if(i===choice&&!ok)b.classList.add('wrong')});$('#feedback').innerHTML=`<div class="result"><b>${ok?'Richtig ✓':'Noch nicht.'}</b><br>${l.q.why}</div>`;await sb.from('quiz_answers').insert({user_id:user.id,lesson_id:lid,question_key:'q1',is_correct:ok});if(ok&&!completed().has(lid)){await sb.from('progress').upsert({user_id:user.id,lesson_id:lid,completed:true,xp_earned:l.xp,completed_at:new Date().toISOString()},{onConflict:'user_id,lesson_id'});await loadState();toast(`+${l.xp} XP`)} }
function renderReview(){let wrong=state.answers.filter(a=>!a.is_correct),ids=[...new Set(wrong.map(a=>a.lesson_id))],ls=allLessons().filter(l=>ids.includes(l.id));$('#content').innerHTML=ls.length?`<div class="grid">${ls.map(l=>`<div class="card third"><span class="tag">WIEDERHOLEN</span><h3>${l.title}</h3><p>${l.module.title}</p><button class="btn" onclick="openLesson('${l.module.id}','${l.id}')">Üben</button></div>`).join('')}</div>`:`<div class="card empty"><h3>Noch keine Fehlerliste 🎯</h3><p>Falsche Quizantworten landen automatisch hier.</p></div>`}
function renderTools(){$('#content').innerHTML=`<div class="grid"><div class="card tool-card half"><h3>Deckungsbeitrag</h3><label>Verkaufspreis (€)<input id="dbp" type="number" step="0.01"></label><label>Variable Kosten (€)<input id="dbv" type="number" step="0.01"></label><button class="btn" onclick="calcDB()">Berechnen</button><div id="dbr" class="result">Ergebnis</div></div><div class="card tool-card half"><h3>Break-even</h3><label>Fixkosten (€)<input id="bef" type="number" step="0.01"></label><label>Preis je Stück (€)<input id="bep" type="number" step="0.01"></label><label>Variable Kosten je Stück (€)<input id="bev" type="number" step="0.01"></label><button class="btn" onclick="calcBE()">Berechnen</button><div id="ber" class="result">Ergebnis</div></div><div class="card tool-card half"><h3>Gewinn & Marge</h3><label>Umsatz (€)<input id="gu" type="number" step="0.01"></label><label>Gesamtkosten (€)<input id="gk" type="number" step="0.01"></label><button class="btn" onclick="calcG()">Berechnen</button><div id="gr" class="result">Ergebnis</div></div><div class="card tool-card half"><h3>Umsatzsteuer</h3><label>Bruttobetrag (€)<input id="ub" type="number" step="0.01"></label><label>Steuersatz<select id="us"><option value="19">19 %</option><option value="7">7 %</option></select></label><button class="btn" onclick="calcU()">Berechnen</button><div id="ur" class="result">Ergebnis</div></div></div>`}
const num=id=>Number($('#'+id).value||0), eur=n=>n.toLocaleString('de-DE',{style:'currency',currency:'EUR'});function calcDB(){let r=num('dbp')-num('dbv');$('#dbr').textContent=`Deckungsbeitrag: ${eur(r)}`};function calcBE(){let db=num('bep')-num('bev');$('#ber').textContent=db>0?`Break-even: ${Math.ceil(num('bef')/db)} Stück`:'Deckungsbeitrag muss positiv sein.'};function calcG(){let g=num('gu')-num('gk'),m=num('gu')?g/num('gu')*100:0;$('#gr').textContent=`Gewinn: ${eur(g)} · Marge: ${m.toFixed(1)} %`};function calcU(){let b=num('ub'),s=num('us')/100,n=b/(1+s);$('#ur').textContent=`Netto: ${eur(n)} · USt: ${eur(b-n)}`}
function renderSimulation(){window.sim=window.sim||{capital:10000,revenue:0,costs:0,month:1};let x=window.sim,g=x.revenue-x.costs;$('#content').innerHTML=`<div class="grid"><section class="card third"><span class="tag">DEIN UNTERNEHMEN</span><h3>Monat ${x.month}</h3><div class="stat-row"><span>Startkapital</span><b>${eur(x.capital)}</b></div><div class="stat-row"><span>Umsatz</span><b class="money positive">${eur(x.revenue)}</b></div><div class="stat-row"><span>Kosten</span><b class="money negative">${eur(x.costs)}</b></div><div class="stat-row"><span>Ergebnis</span><b>${eur(g)}</b></div></section><section class="card half"><span class="tag">ENTSCHEIDUNG</span><h3>Dein erster Geschäftsmonat</h3><p>Du hast 10.000 € Kapital. Welche Investition setzt du zuerst um?</p><div class="sim-choice"><button onclick="simDecision('machine')"><b>Maschine kaufen</b><br><small>5.000 € Kosten · +7.500 € Umsatzchance</small></button><button onclick="simDecision('marketing')"><b>Marketing starten</b><br><small>2.500 € Kosten · +4.000 € Umsatzchance</small></button><button onclick="simDecision('staff')"><b>Mitarbeiter einstellen</b><br><small>2.000 € Kosten · +3.500 € Umsatzchance</small></button><button onclick="simDecision('reserve')"><b>Liquidität halten</b><br><small>0 € Kosten · geringeres Risiko</small></button></div></section><section class="card third"><h3>Lernziel</h3><p class="muted">Die Simulation zeigt dir, warum Wachstum, Gewinn und Liquidität unterschiedliche Dinge sind. Die Werte sind Lernbeispiele, keine Geschäftsprognose.</p><button class="btn secondary" onclick="window.sim={capital:10000,revenue:0,costs:0,month:1};renderSimulation()">Simulation zurücksetzen</button></section></div>`}
function simDecision(type){let x=window.sim||{capital:10000,revenue:0,costs:0,month:1},map={machine:[5000,7500],marketing:[2500,4000],staff:[2000,3500],reserve:[0,500]};let [c,r]=map[type];if(c>x.capital){toast('Nicht genug Liquidität');return}x.capital-=c;x.costs+=c;x.revenue+=r;x.capital+=r;x.month++;window.sim=x;toast(`Entscheidung ausgewertet: ${eur(r-c)} Ergebnis`);renderSimulation()}
function renderProfile(){let done=completed().size,total=allLessons().length;$('#content').innerHTML=`<div class="grid"><div class="card third"><h3>Level ${level()}</h3><p class="muted">Je 250 XP steigst du ein Level.</p><b>${xp()} XP</b></div><div class="card third"><h3>${done}/${total}</h3><p class="muted">Lektionen abgeschlossen</p></div><div class="card third"><h3>${state.answers.filter(a=>a.is_correct).length}</h3><p class="muted">Richtige Antworten</p></div><div class="card wide"><h3>Modulfortschritt</h3>${modules.map(m=>{let d=m.lessons.filter(l=>completed().has(l.id)).length;return `<div class="stat-row"><span>${m.title}</span><b>${d}/${m.lessons.length}</b></div>`}).join('')}</div></div>`}
init();
