-- RUDELBAR AKADEMIE v136: Einmalig im SQL Editor des BESTEHENDEN Rudelbar-Supabase-Projekts ausführen.
-- Erst DB-Backup erstellen. Keine bestehenden Tabellen werden gelöscht.
-- Voraussetzung: Die vorhandene RPC public.get_rudelbar_role() existiert.

create or replace function public.academy_is_superuser()
returns boolean language sql stable security invoker set search_path = public, pg_temp as $$
  select coalesce(public.get_rudelbar_role() = 'superuser',false);
$$;
revoke all on function public.academy_is_superuser() from public;
grant execute on function public.academy_is_superuser() to authenticated;

create table if not exists public.academy_access (
  user_id uuid not null references auth.users(id) on delete cascade,
  area text not null check(area in ('unternehmer','marketing','mobile-kneipe','security')),
  primary key(user_id,area)
);
alter table public.academy_access enable row level security;
revoke all on public.academy_access from anon;
grant select on public.academy_access to authenticated;
drop policy if exists academy_access_read on public.academy_access;
create policy academy_access_read on public.academy_access for select to authenticated
  using (user_id = (select auth.uid()) or (select public.academy_is_superuser()));

-- Nur Server-RPC kann Freigaben ändern; kein direktes Client-INSERT/UPDATE/DELETE.
create or replace function public.academy_set_access(p_user_id uuid,p_areas text[])
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if auth.uid() is null or not public.academy_is_superuser() then
    raise exception 'Nur Superuser dürfen Akademie-Rechte ändern' using errcode='42501';
  end if;
  if p_user_id is null or p_areas is null or exists(
    select 1 from unnest(p_areas) a where a not in ('unternehmer','marketing','mobile-kneipe','security')
  ) then raise exception 'Ungültige Lernbereiche'; end if;
  if not exists(select 1 from auth.users where id=p_user_id) then
    raise exception 'Benutzer existiert nicht';
  end if;
  delete from public.academy_access where user_id=p_user_id;
  insert into public.academy_access(user_id,area)
  select p_user_id,distinct_area from (select distinct unnest(p_areas) as distinct_area) x;
end;
$$;
revoke all on function public.academy_set_access(uuid,text[]) from public,anon;
grant execute on function public.academy_set_access(uuid,text[]) to authenticated;

-- Fortschritt getrennt nach bereits bestehenden Rudelbar-Benutzerkonten.
create table if not exists public.progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  completed boolean not null default false,
  xp_earned integer not null default 0 check(xp_earned>=0),
  completed_at timestamptz,
  unique(user_id,lesson_id)
);
create table if not exists public.quiz_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  question_key text not null,
  is_correct boolean not null,
  created_at timestamptz not null default now()
);
alter table public.progress enable row level security;
alter table public.quiz_answers enable row level security;
revoke all on public.progress, public.quiz_answers from anon;
grant select,insert,update on public.progress to authenticated;
grant select,insert on public.quiz_answers to authenticated;
grant usage,select on sequence public.progress_id_seq to authenticated;
grant usage,select on sequence public.quiz_answers_id_seq to authenticated;
drop policy if exists rudelbar_academy_progress_select on public.progress;
drop policy if exists rudelbar_academy_progress_insert on public.progress;
drop policy if exists rudelbar_academy_progress_update on public.progress;
drop policy if exists rudelbar_academy_answers_select on public.quiz_answers;
drop policy if exists rudelbar_academy_answers_insert on public.quiz_answers;
create policy rudelbar_academy_progress_select on public.progress for select to authenticated using (user_id=(select auth.uid()));
create policy rudelbar_academy_progress_insert on public.progress for insert to authenticated with check (user_id=(select auth.uid()));
create policy rudelbar_academy_progress_update on public.progress for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy rudelbar_academy_answers_select on public.quiz_answers for select to authenticated using (user_id=(select auth.uid()));
create policy rudelbar_academy_answers_insert on public.quiz_answers for insert to authenticated with check (user_id=(select auth.uid()));
